In [26]:
import great_expectations as ge
import pandas as pd
from great_expectations.data_context import FileDataContext

In [27]:
df = pd.read_csv('P2M3_Rezha_Aulia_data_clean.csv')

print(df.columns.tolist())
print(f'\nShape: {df.shape}')
print(f'\nSample Data:')
df.head()

['vin', 'county', 'city', 'state', 'postal_code', 'model_year', 'make', 'model', 'electric_vehicle_type', 'cafv_eligibility', 'electric_range', 'base_msrp', 'legislative_district', 'dol_vehicle_id', 'vehicle_location', 'electric_utility', 'census_tract']

Shape: (130138, 17)

Sample Data:

,vin,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,census_tract
0,5YJXCAE26J,Yakima,Yakima,WA,98908.0,2018.0,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238.0,0.0,14.0,141151601.0,POINT (-120.56916 46.58514),PACIFICORP,5.307700e+10
1,JHMZC5F37M,Kitsap,Poulsbo,WA,98370.0,2021.0,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47.0,0.0,23.0,171566447.0,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EB0K,King,Seattle,WA,98199.0,2019.0,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,36.0,9426525.0,POINT (-122.40092 47.65908),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,1N4AZ0CP5D,King,Seattle,WA,98119.0,2013.0,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75.0,0.0,36.0,211807760.0,POINT (-122.3684 47.64586),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,5YJSA1E21H,Thurston,Lacey,WA,98516.0,2017.0,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210.0,0.0,22.0,185810306.0,POINT (-122.75379 47.06316),PUGET SOUND ENERGY INC,5.306701e+10

In [28]:
# Data Context
context = FileDataContext.create(project_root_dir='./')

In [29]:
# Data Source
datasource_name = 'ev-data'
datasource = context.sources.add_pandas(datasource_name)

# Data asset
asset_name = 'ev-clean-data'
path_to_data = 'P2M3_Rezha_Aulia_data_clean.csv'
asset = datasource.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)

# Batch Request
batch_request = asset.build_batch_request()

In [30]:
# Expectation suite
expectation_suite_name = 'expectation-ev-data'
context.add_or_update_expectation_suite(expectation_suite_name)

# Validator
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name
)

validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,vin,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,cafv_eligibility,electric_range,base_msrp,legislative_district,dol_vehicle_id,vehicle_location,electric_utility,census_tract
0,5YJXCAE26J,Yakima,Yakima,WA,98908.0,2018.0,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238.0,0.0,14.0,141151601.0,POINT (-120.56916 46.58514),PACIFICORP,5.307700e+10
1,JHMZC5F37M,Kitsap,Poulsbo,WA,98370.0,2021.0,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47.0,0.0,23.0,171566447.0,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EB0K,King,Seattle,WA,98199.0,2019.0,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,36.0,9426525.0,POINT (-122.40092 47.65908),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,1N4AZ0CP5D,King,Seattle,WA,98119.0,2013.0,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75.0,0.0,36.0,211807760.0,POINT (-122.3684 47.64586),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,5YJSA1E21H,Thurston,Lacey,WA,98516.0,2017.0,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210.0,0.0,22.0,185810306.0,POINT (-122.75379 47.06316),PUGET SOUND ENERGY INC,5.306701e+10

## Expectation 1 : to_be_unique

In [31]:
# Expectation 1 : dol_vehicle_id harus unik 
# DOL Vehicle ID adalah identifikasi unik setiap kendaraan yang diterbitkan oleh Washington State
validator.expect_column_values_to_be_unique(column='dol_vehicle_id')

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 130138,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 2 : to_be_between

In [33]:
# Expectation 2 : Electric Vehicle Range harus antara 0 dan 337 miles
# Jarak yang bisa ditempuh baterai EV tidak mungkin negatif dan juga tidak melebihi jarak max dataset
validator.expect_column_values_to_be_between(
    column='electric_range',
    min_value=0,
    max_value=337
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 130138,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 3 : to_be_in_set

In [34]:
# Expectation 3 : electric_vehicle_type hanya ada BEV atau PHEV
# Hanya ada 2 tipe kendaraan listrik yang terdaftar di Washington State
validator.expect_column_values_to_be_in_set(
    column='electric_vehicle_type',
    value_set=[
        'Battery Electric Vehicle (BEV)',
        'Plug-in Hybrid Electric Vehicle (PHEV)'
    ]
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 130138,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 4 : to_be_in_type_list

In [35]:
# Expectation 4 : electric_range harus bertipe numerik
# Kolom electric_range harus berupa angka untuk keperluan analisis dan perhitungan
validator.expect_column_values_to_be_in_type_list(
    column='electric_range',
    type_list=['int64', 'float64', 'int', 'float']
)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "float64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 5 : expect_column_value_lenghts_to_be_between

In [36]:
# Expectation 5 : Panjang karakter kolom vin harus antara 5 dan 10
# Kolom VIN (1-10) berisi 10 karakter pertama dari Vehicle Identification Number
# Panjang karakternya tidak boleh kurang dari 5 atau lebih dari 10

validator.expect_column_value_lengths_to_be_between(
    column='vin',
    min_value=5,
    max_value=10
)

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 130138,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 6 : expect_column_values_to_match_regex

In [37]:
# Expectation 6 : State harus berisi 2 huruf kapital
# Setelah filter hanya Washington State (WA), semua nilai state harusnya kode negara bagian
# 2 huruf kapital adalah formatnya USPS

validator.expect_column_values_to_match_regex(
    column='state',
    regex='^[A-Z]{2}$'
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 130138,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

## Expectation 7 : expect_column_proportion_of_unique_values_to_be_between

In [38]:
# Expectation 7 : Proporsi nilai unik kolom 'make' harus antara 0.0001 dan 0.01
# Kolom make berisi nama merek kendaraan dengan jumlah yang terbatas
validator.expect_column_proportion_of_unique_values_to_be_between(
    column='make',
    min_value=0.0001,
    max_value=0.01
)

Calculating Metrics:   0%|          | 0/7 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": 0.0002689452734789224
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [39]:
validator.save_expectation_suite(discard_failed_expectations=False)
print('Expectation suite berhasil disimpan')

Expectation suite berhasil disimpan